version: "3"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - strapi-pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  strapi-pgdata:
    driver: local
